# .github/workflows/welcome.yml

name: Welcome First-Timers

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome new contributor
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const message = `Hey @${pr.user.login}! 🎉 Thank you so much for your first contribution to Developer's Toolkit! We're thrilled to have you here.\n\nI'll review your pull request as soon as possible. Meanwhile, feel free to check out other issues.\n\nWelcome to the community! 🚀`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: message
            });